# Generated by Django 2.1.7 on 2019-02-18 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prof',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='prof_department', to='courses.Department'),
        ),
        migrations.RemoveField(
            model_name='prof',
            name='courses',
        ),
        migrations.AddField(
            model_name='prof',
            name='courses',
            field=models.ManyToManyField(related_name='prof_courses', to='courses.Course'),
        ),
    ]
