# Generated by Django 2.1.7 on 2019-02-19 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20190218_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='prof',
            name='avatar',
            field=models.ImageField(blank=True, default='user_generic2_black.png', help_text='Prof Headshot', null=True, upload_to='avatars', verbose_name='Headshot'),
        ),
        migrations.AddField(
            model_name='prof',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, default='100', editable=False, null=True),
        ),
        migrations.AddField(
            model_name='prof',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, default='100', editable=False, null=True),
        ),
    ]
